export const VIDEO_SET_ALL_VIDEOS = 'VIDEO:SET_ALL_VIDEOS';
export const VIDEO_SET_CURRENT_VIDEO_ID = 'VIDEO:SET_CURRENT_VIDEO_ID';
export const VIDEO_SET_CURRENT_VIDEO_DATA = 'VIDEO:SET_CURRENT_VIDEO_DATA';

export const USER_SET_AUTH = 'USER:SET_AUTH';
export const USER_SET_DATA = 'USER:SET_DATA';
